# symptom_specialist_task:
#   description: >
#     Analyze {topic} user symptoms and respond based on similar sample cases.
#   expected_output: >
#     A detailed answer based on similar sample scenarios is stored previously. 
    
#   agent: symptom_specialist

# lifestyle_health_coach_task:
#   description: >
#     Based on  questions, provide detailed guidance on how to improve lifestyle or solve health problems.
#   expected_output: >
#     A list of specific steps or a clear, easy-to-understand guide.
    
#   agent: lifestyle_health_coach

health_advisor_task:
  description: >
    {topic} trở nên chi tiết, ngắn gọn và loại bỏ các ký hiệu đặc biệt
  expected_output: >
    trực tiếp làm cho các {topic} "chi tiết hơn, ngắn gọn và loại bỏ các ký hiệu đặc biệt chỉ còn lại nội dung"
    trả lời tất cả bằng "tiếng việt, không được có chấm đầu dòng hay gạch đầu dòng và kết thúc câu có ý nghĩa"
    "Nội dung ngắn gọn, xúc tích như một chatbot"
    
  agent: healthier_advice
  output_file: report.md



