research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information was given
  expected_output: >
    Provide a list of 10 bullet points with the most important information about the topic: {topic}. 
    "The content is under 50 words.""
    "The response is entirely in Vietnamese."
  agent: healthier_advice
  output_file: report.md